import React from "react";

function Chatbot({ disease, response }) {
  return (
    <div className="card chatbot-card">
      <div className="chatbot-header">
        <div className="chatbot-icon">🤖</div>
        <h3>AI Agri-Advisor</h3>
      </div>

      <div className="chatbot-body">
        {response || `Hello! I'm analyzing the ${disease} issue. Please wait a moment...`}
      </div>

      <div className="chatbot-footnote">
        * Advice generated by AI. Please consult a local expert before large scale application.
      </div>
    </div>
  );
}

export default Chatbot;
